### ISSUE TITLE
connect to a monero，

### ISSUE THREAD

**Issue by carrie143** [ExcitableAardvark/node-monero-rpc#8]
when I run the command for start the wallet rpc,it returned ' This is the RPC monero wallet. It needs to connect to a monero' what I should do?

**Comment by ExcitableAardvark** [comment]
You need to run the wallet RPC server *and* the daemon. If you don't want to run a daemon, you can add `--daemon-address geo.node.moneroworld.com:18089` to the end of the `monero-wallet-rpc` command. However, this reduces privacy and slows down syncing.

**Comment by carrie143** [comment]
thank you,I try your advice,and it works~and can I ask you some questions?one:In monero,an monero address have a private key,yes or no?two:can I get the confimation of a transation by txid?three:can I get any address's balance By address,not only the address in a wallet

**Comment by ExcitableAardvark** [comment]
>In monero,an monero address have a private key,yes or no

Yes.

>can I get the confimation of a transation by txid

Yes. You need to use `get_transfer_by_txid` and then you need to look at `transfer.height`. If `transfer.height` is 0, the transaction is unconfirmed.

>can I get any address's balance By address,not only the address in a wallet

No, this is not possible with Monero.
