### ISSUE TITLE
transfer problem

### ISSUE THREAD

**Issue by carrie143** [ExcitableAardvark/node-monero-rpc#9]
1.I hava run the ./monero-wallet-rpc 
2.I want to send some monero from my wallet to another wallet,
my code:
----------
const Wallet = require('monero-rpc').Wallet
const wallet = new Wallet('http://localhost:18083')
wallet.getAddress((err, address) => {
    if (err) return console.log(err)
    console.log(address) // '46tFLJPaNyy...'
})
wallet.transfer({
    destinations: [
        { address: '492xPwbbNuP5JNZK6nsuYDfGFC8BbiCsUbbqHKWb5rsUSp38Ex3hH9JXG3bCEbkkH7eDq1YE3qfdJNaXSrnW8tN5LeZFcsd', amount: 100000000000}
    ],
    mixin: 7, // default 7
    priority: 0 // default 0
}, (err, result) => {
    if (err) return console.log(err)
    console.log(result.fee) // 48958481211
    console.log(result.tx_hash) // '985180f46863...'
})
-----------
when I run the code ,return nothing .expectd the result.fee and result.tx_hash,I do not know transfer successfully or not?

**Comment by ExcitableAardvark** [comment]
* What does this code print? `undefined`, or does it just hang forever?
* Do you see any errors in the `monero-wallet-rpc` window?
* Finally, please can you import your private key into the CLI or GUI wallet to see if the transfer was sent at all?
